-- Berater-Rolle + Stoß-Profil pro Wochentag (Mo–So)
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'ADVISOR';
ALTER TYPE "InviteRole" ADD VALUE IF NOT EXISTS 'ADVISOR';

ALTER TABLE "Company"
ADD COLUMN IF NOT EXISTS "peakDayLevels" TEXT[] NOT NULL DEFAULT ARRAY['NORMAL', 'NORMAL', 'NORMAL', 'NORMAL', 'NORMAL', 'NORMAL', 'NORMAL']::TEXT[];
